display_name = "Metaphone"
library_name = "metaphone"
version = "0.5"
author = "Alastair Houghton"
author_email = "alastair@alastairs-place.net"
license = "BSD"
url = "https://github.com/oubiwann/metaphone"
description = "A Python implementation of the double metaphone algorithms."
