display_name = "Double Metaphone"
library_name = "metaphone"
version = "0.4"
author = "Andrew Collins"
author_email = "AtomBoy@SWCP.com"
license = "BSD"
url = "https://github.com/oubiwann/double-metaphone"
description = "A Python implementation of the double-metaphone algorithm."
